
char* global_css =
"* {     \n"
    "       background-color: black;\n"
    "       color: #fffec0;\n"
    "       font-size: 32px;\n"
    "       font-weight: 800;\n"
    "}\n"
    ".redbk, .redbk *\n"
    "{\n"
    "   background-color: #990000;\n"
    "}\n"
    ".pwr\n"
    "{\n"
    "   background-image: url(\"/home/pi/pwr.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".pwrr\n"
    "{\n"
    "   background-image: url(\"/home/pi/pwrr.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".fire\n"
    "{\n"
    "   background-image: -gtk-gradient(linear,\n"
    "                                   left top,\n"
    "                                   right top,\n"
    "                       from (#000000),\n"
    "                       color-stop (0.25, #0000ff),\n"
    "                       color-stop (0.33, #990099),\n"
    "                       color-stop (0.5, #ff0000),\n"
    "                       color-stop (0.75, #ffff00),\n"
    "                       to (#ffffff)\n"
    "                                  );\n"
    "   color: #000;\n"
    "}\n"
    ".fever\n"
    "{\n"
    "   background-image: -gtk-gradient(linear,\n"
    "                                   left top,\n"
    "                                   right top,\n"
    "                       from (#000000),\n"
    "                       color-stop (0.50, #0000ff),\n"
    "                       color-stop (0.55, #00ff00),\n"
    "                       color-stop (0.60, #ff0000),\n"
    "                       to (#000000)\n"
    "                                  );\n"
    "   color: #fff;\n"
    "}\n"
    ".bleu\n"
    "{\n"
    "   background-image: -gtk-gradient(linear,\n"
    "                                   left top,\n"
    "                                   right top,\n"
    "                       from (#000000),\n"
    "                       color-stop (0.25, #003333),\n"
    "                       color-stop (0.33, #336666),\n"
    "                       color-stop (0.51, #99ffff),\n"
    "                       color-stop (0.75, #ffeeee),\n"
    "                       to (#ffffff)\n"
    "                                  );\n"
    "   color: #000;\n"
    "}\n"
    ".tiv\n"
    "{\n"
    "   background-image: -gtk-gradient(linear,\n"
    "                                   left top,\n"
    "                                   right top,\n"
    "                       from (#0099ff),\n"
    "                       to (#ff9966)\n"
    "                                  );\n"
    "   color: #000;\n"
    "}\n"
    ".hues\n"
    "{\n"
    "   background-image: -gtk-gradient(linear,\n"
    "                                   left top,\n"
    "                                   right top,\n"
    "                       from (#000),\n"
    "                       color-stop (0.16, #0000ff),\n"
    "                       color-stop (0.24, #00cccc),\n"
    "                       color-stop (0.33, #00ff00),\n"
    "                       color-stop (0.50, #ff00ff),\n"
    "                       color-stop (0.67, #ffff00),\n"
    "                       color-stop (0.83, #ff0000),\n"
    "                       to (#fff)\n"
    "                                  );\n"
    "   color: #000;\n"
    "}\n"
    ".ugb\n"
    "{\n"
    "   background-image: url(\"/home/pi/ugb180.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".cuv\n"
    "{\n"
    "   background-image: url(\"/home/pi/gbu180.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".mono\n"
    "{\n"
    "   background-image: url(\"/home/pi/mono180.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".veg\n"
    "{\n"
    "   background-image: url(\"/home/pi/bgu180.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".raw\n"
    "{\n"
    "   background-image: url(\"/home/pi/raw180.jpg\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".bee\n"
    "{\n"
    "   background-image: url(\"/home/pi/bee180.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".ugb *, .cuv *, .mono *, .veg *, .raw *, .bee *,\n"
    ".ugbbig *, .cuvbig *, .monbig *, .rawbig *, .beebig *\n"
    "{\n"
    "   background-color: transparent;\n"
    "   color: #00f;\n"
    "}\n"
    
    ".ugbbig *, .cuvbig *, .monbig *, .rawbig *, .beebig *\n"
    "{\n"
    "   font-size: 53px;\n"
    "   font-weight: bold;\n"
    "   padding-top: 123px;\n"
    "   color: #fff;\n"
    "}\n"
    
    ".ugbbig\n"
    "{\n"
    "   background-image: url(\"/home/pi/ugb360.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".beebig\n"
    "{\n"
    "   background-image: url(\"/home/pi/bee360.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".cuvbig\n"
    "{\n"
    "   background-image: url(\"/home/pi/gbu360.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".monbig\n"
    "{\n"
    "   background-image: url(\"/home/pi/mono360.png\");\n"
    "   background-color: transparent;\n"
    "}\n"
    ".rawbig\n"
    "{\n"
    "   background-image: url(\"/home/pi/raw360.jpg\");\n"
    "   background-color: transparent;\n"
    "}\n"
    
    ".gri *\n"
    "{\n"
    "   background-color: transparent;\n"
    "   color: #cfc;\n"
    "}\n"
    ".tinytxt, .tinytxt *\n"
    "{\n"
    "   font-size: 22px;\n"
    "}\n"
    ".smtxt, .smtxt *\n"
    "{\n"
    "   font-size: 28px;\n"
    "}\n"
    ".ifon, .ifon *\n"
    "{\n"
    "   background-color: #9966ff;\n"
    "   color: #000;\n"
    "}\n"
    ".vfon, .vfon *\n"
    "{\n"
    "   background-color: #ffff99;\n"
    "   color: #000;\n"
    "}\n"
    ;
    
